In [96]:
import sys
import numpy as np
print('Python: {}'.format(sys.version))
print ('Numpy: {}'.format(np.__version__))

Python: 3.9.0 (default, Sep  7 2024, 08:23:43) 
[GCC 11.4.0]
Numpy: 2.0.2


In [97]:
x = 6
x

6

In [98]:
# defining a vector
x = np.array((1,2,3))
x

array([1, 2, 3])

In [99]:
print('Vector Dimensions: {}'.format(x.shape))
print('Vector Size: {}'.format(x.size))

Vector Dimensions: (3,)
Vector Size: 3


In [100]:
# defining a matrix
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [101]:
print('Vector Dimensions: {}'.format(x.shape))
print('Vector Size: {}'.format(x.size))

Vector Dimensions: (3, 3)
Vector Size: 9


In [102]:
# define a matrix of a given dimension
x = np.ones((5,3))
x 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
print('Vector Dimensions: {}'.format(x.shape))
print('Vector Size: {}'.format(x.size))

Vector Dimensions: (5, 3)
Vector Size: 15


In [104]:
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [105]:
print('Tensors Dimensions: {}'.format(x.shape))
print('Tensor Size: {}'.format(x.size))

Tensors Dimensions: (3, 3, 3)
Tensor Size: 27


In [106]:
# indexing
A = np.ones((5,5), dtype=int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [107]:
A[0,1]=2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [108]:
A[:,0] =3
A

array([[3, 2, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1]])

In [109]:
A[:,:] = 5
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [110]:
# for higher dimensions, simply add an index
A = np.ones((5,5,5),dtype=int)
# assing first row a new value
A[:,0,0] = 6
A

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [111]:
# matrix oeprations
A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2), dtype=int)


In [112]:
A

matrix([[1, 2],
        [3, 4]])

In [113]:
B

array([[1, 1],
       [1, 1]])

In [114]:
# Element wise sum
C = A + B

In [115]:
C

matrix([[2, 3],
        [4, 5]])

In [116]:
# Element wise subtraction
C = A - B
C

matrix([[0, 1],
        [2, 3]])

In [117]:
C = A * B
C

matrix([[3, 3],
        [7, 7]])

In [118]:
# the matrix transpose
A = np.array(range(9))
A = A.reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [119]:
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [120]:
C = B.T
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [121]:
A = np.array(range(10))
A = A.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [122]:
B = A.T
B

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [125]:
B.shape

(5, 2)

In [126]:
A.shape

(2, 5)

In [127]:
# tensors!
A = np.ones((3,3,3,3,3,3,3,3,3,3))
A

array([[[[[[[[[[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]],

              [[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]],

              [[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]]],


             [[[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]],

              [[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]],

              [[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]]],


             [[[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]],

              [[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]],

              [[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]]]],



            [[[[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]],

              [[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]],

             

In [128]:
A.shape

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)

In [129]:
len(A.shape)

10

In [130]:
A.size

59049