In [54]:
import numpy as np

In [55]:

X = np.array([1,2])
print('X:',X)
W = np.array([0.1, 0.2])
print('W:',W)

X: [1 2]
W: [0.1 0.2]


In [56]:
X * W

array([0.1, 0.4])

In [57]:
np.sum(X * W)

np.float64(0.5)

In [58]:
np.dot(X, W)

np.float64(0.5)

In [59]:
X @ W

np.float64(0.5)

In [60]:
X.dot(W)

np.float64(0.5)

In [61]:
"""
In the modern sense, the perceptron is an algorithm for learning a binary classifier called a threshold function: a function that maps its input
f(x) ={1 if W . x + b >0
      { 0 otherwise
where  w  is a vector of real-valued weights,  w ⋅ x is the dot product  where m is the number of inputs to the perceptron, and b is the bias.The bias shifts the decision boundary away from the origin and does not depend on any input value.
m


"""

'\nIn the modern sense, the perceptron is an algorithm for learning a binary classifier called a threshold function: a function that maps its input\nf(x) ={1 if W . x + b >0\n      { 0 otherwise\nwhere  w  is a vector of real-valued weights,  w ⋅ x is the dot product  where m is the number of inputs to the perceptron, and b is the bias.The bias shifts the decision boundary away from the origin and does not depend on any input value.\nm\n\n\n'

In [62]:
def and_gate(x1, x2): 
    w1, w2, th = 0.5, 0.5, 0.7 
    result = x1 * w1 + x2 * w2 
    if result > th: 
        y = 1
    else: 
        y = 0 

    return y 

In [63]:
and_gate(x1=0, x2=0)

0

In [64]:
and_gate(x1=0, x2=1)

0

In [65]:
and_gate(x1=1, x2=0)

0

In [66]:
and_gate(x1=1, x2=1)

1

In [67]:
def and_gate2(x1, x2):
    w1, w2, th = 0.1, 0.1, 0.1 
    result = x1 * w1 + x2 * w2 
    y = 1 if result > th else 0 
    return y 

In [68]:
and_gate2(1, 1)

1

In [69]:
def and_gate3(x):
    w = np.array([0.5, 0.5])
    th = 0.7
    # y = 1 if np.sum(x * w) > th else 0 
    y = 1 if np.dot(x, w) > th else 0 
    return y 

In [70]:
and_gate3(np.array([0.5, 0.5]))

0

In [71]:
def and_gate4(X):
    w = np.array([0.5, 0.5])  # 가중치(weight)
    th = 0.7
    y = (np.dot(X, w) > th).astype(np.int_)
    return y 

In [72]:
X = np.array([[0, 0],[0, 1],[1, 0],[1, 1]])

In [73]:
and_gate4(X)

array([0, 0, 0, 1])

In [74]:
def and_gate5(X):
    w = np.array([0.5, 0.5])  # 가중치 
    b = -0.7  # 편향 
    result = np.dot(X, w) + b # Linear equation 
    y = result > 0 
    return y.astype(np.int_)

In [75]:
and_gate5(X)

array([0, 0, 0, 1])