In [63]:
import tensorflow as tf

In [64]:
tf.enable_eager_execution()

In [65]:
x = tf.constant(11)
y = tf.constant(11)
z = x*y
print(z)

tf.Tensor(121, shape=(), dtype=int32)


In [66]:
z.numpy()

121

Math operations in TensorFlow

Use tf.add to add two numbers:

In [67]:
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])
sum = tf.add(x,y)
sum.numpy()

array([4., 4., 4.], dtype=float32)

The tf.subtract function is used for finding the difference between two numbers:

In [68]:
difference = tf.subtract(x,y)
difference.numpy()

array([-2.,  0.,  2.], dtype=float32)

The tf.multiply function is used for multiplying two numbers:

In [69]:
product = tf.multiply(x,y)
product.numpy()


array([3., 4., 3.], dtype=float32)

Divide two numbers using tf.divide:

In [70]:
division = tf.divide(x,y)
division.numpy()

array([0.33333334, 1.        , 3.        ], dtype=float32)

The dot product can be computed as follows:

In [71]:
dot_product = tf.reduce_sum(tf.multiply(x, y))
dot_product.numpy()

10.0

Next, let’s find the index of the minimum and maximum elements:

In [72]:
x = tf.constant([10, 0, 13, 9])
tf.argmin(x).numpy()

1

In [73]:
tf.argmax(x).numpy()

2

Run the following code to find the squared difference between x and y:

In [74]:
x = tf.Variable([1,3,5,7,11])
y = tf.Variable([1])
tf.math.squared_difference(x,y).numpy()

array([  0,   4,  16,  36, 100], dtype=int32)

Let’s try typecasting; that is, converting from one data type into another.

In [75]:
print(x.dtype)

<dtype: 'int32'>


We can convert the type of x, which is tf.int32, into tf.float32, using tf.cast, as shown in the following code:

In [76]:
x = tf.cast(x, dtype=tf.float32)
print(x.dtype)

<dtype: 'float32'>


Concatenate the two matrices:

In [77]:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]

Concatenate the matrices row-wise:

In [78]:
tf.concat([x, y], 0).numpy()

array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]], dtype=int32)

Use the following code to concatenate the matrices column-wise:

In [79]:
tf.concat([x, y], 1).numpy()

array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]], dtype=int32)

Stack the x matrix using the stack function:

In [80]:
tf.stack(x, axis=1).numpy()

array([[3, 7],
       [6, 7],
       [9, 7]], dtype=int32)

Now, let’s see how to perform the reduce_mean operation:

In [81]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

Compute the mean value of x; that is, (1.0 + 5.0 + 2.0 + 3.0) / 4:

In [82]:
tf.reduce_mean(input_tensor=x).numpy()

2.75

Compute the mean across the row; that is, (1.0+5.0)/2, (2.0+3.0)/2:

In [83]:
tf.reduce_mean(input_tensor=x, axis=0).numpy()

array([1.5, 4. ], dtype=float32)

Compute the mean across the column; that is, (1.0+5.0)/2.0, (2.0+3.0)/2.0:

In [84]:
tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy()

array([[3. ],
       [2.5]], dtype=float32)

Draw random values from the probability distributions:

In [85]:
tf.random.normal(shape=(3,2), mean=10.0, stddev=2.0).numpy()

array([[12.687916, 10.834997],
       [11.713821, 12.370404],
       [ 9.326105,  9.445396]], dtype=float32)

Compute the softmax probabilities:

In [86]:
x = tf.constant([7., 2., 5.])
tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

Define the square function:

In [87]:
def square(x):
    return tf.multiply(x, x)

The gradients can be computed for the preceding square function using tf.GradientTape

In [88]:
with tf.GradientTape(persistent=True) as tape:
    print(square(6.).numpy())

36.0
